#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2027.0.0a2"

# Run tests in isolated mode to prevent hanging and weird errors
pyfrc.isolated = true

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all",
     "apriltag",
     "commands2",
    "cscore",
     "navx",
    # "pathplannerlib",
    # "playingwithfusion",
    # "romi",
    "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
    "phoenix6==25.90.0a2", "numpy~=2.1", "robotpy-rev==2027.0.0a1","sleipnirgroup-choreolib==2027.0.0a1" # "photonlibpy==2025.1.1"
]
