#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.1"

# Run tests in isolated mode to prevent hanging and weird errors
pyfrc.isolated = true

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
components = [
    # "all",
     "apriltag",
     "commands2",
    # "romi",
    "sim",
    # "xrp",
]

# Other pip packages to install
requires = [
    "phoenix6", "robotpy-rev","sleipnirgroup-choreolib", "photonlibpy==2026.1.1rc4"
]

[tool.pytest.ini_options]
markers = [
    "integration_test: marks tests as integration tests",
    "slow_integration_test: marks tests as slow integration tests",
]
addopts = "--strict-markers -v --maxfail=2"
faulthandler_timeout = 60
pythonpath = "."
testpaths = ["tests"]
xfail_strict = true

