name: Copy Lemonlib to LemonLib Repo

on:
  push:
    paths:
      - 'src/lemonlib/**'

jobs:
  copy-lemonlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Lemonlib
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "src/lemonlib/"               # Folder to copy
          destination_repo: "FRC5113/LemonLib"       # Target repo
          destination_folder: "/"                    # Destination folder
          destination_branch: "main"                 # <<< DEPLOY TO THIS BRANCH
          user_email: "rradtke1208@gmail.com"
          user_name: "Ryanforce08"
          commit_message: ${{ github.event.head_commit.message }}
          git_server: "github.com"
